
.PHONY: all outherclean

UVMMODE?=# ('none' or object), lib, or shared.
UVMTARGET?=#

include ./Makefrag

UCOMMONPATH?=./../ucommon

INCLUDES=-I$(UCOMMONPATH)


all: $(OBJECTS)


include ./../MakefragRM

outherclean:


include ./../MakefragCommon
