
#ifndef UVMINSTR_H
#define UVMINSTR_H

#include <stddef.h>
#include "uvmcompi.h"
#include "uvmendia.h"

#ifdef __cplusplus
extern "C" {
#endif

typedef enum uvm_instruction_e
{

    UVM_INSTRUCTION_NOOP,
    UVM_INSTRUCTION_HALT,

    UVM_INSTRUCTION_UVMID ,
    UVM_INSTRUCTION_UVMSTS,
    UVM_INSTRUCTION_CTXID ,
    UVM_INSTRUCTION_CTXSTS,

    UVM_INSTRUCTION_GESTKS,
    UVM_INSTRUCTION_GESTKB,
    UVM_INSTRUCTION_GESTKP,
    UVM_INSTRUCTION_SESTKS,
    UVM_INSTRUCTION_SESTKB,
    UVM_INSTRUCTION_SESTKP,

    UVM_INSTRUCTION_GEIM,
    UVM_INSTRUCTION_SEIM,
    UVM_INSTRUCTION_CLIM,

    UVM_INSTRUCTION_MEMORY,
    UVM_INSTRUCTION_BLOCK ,
    UVM_INSTRUCTION_GROW  ,
    UVM_INSTRUCTION_SWAP  ,

    UVM_INSTRUCTION_BYPUSH,
    UVM_INSTRUCTION_BYDROP,
    UVM_INSTRUCTION_BYDUP ,
    UVM_INSTRUCTION_BYREV ,

    UVM_INSTRUCTION_BYADD ,
    UVM_INSTRUCTION_BYSUB ,
    UVM_INSTRUCTION_BYMUL ,
    UVM_INSTRUCTION_BYDIV ,
    UVM_INSTRUCTION_BYMOD ,
    UVM_INSTRUCTION_BYADDS,
    UVM_INSTRUCTION_BYSUBS,
    UVM_INSTRUCTION_BYMULS,
    UVM_INSTRUCTION_BYDIVS,
    UVM_INSTRUCTION_BYMODS,
    UVM_INSTRUCTION_BYASL ,
    UVM_INSTRUCTION_BYASR ,
    UVM_INSTRUCTION_BYAND ,
    UVM_INSTRUCTION_BYOR  ,
    UVM_INSTRUCTION_BYXOR ,
    UVM_INSTRUCTION_BYNOT ,
    UVM_INSTRUCTION_BYLSL ,
    UVM_INSTRUCTION_BYLSR ,
    UVM_INSTRUCTION_BYRL  ,
    UVM_INSTRUCTION_BYRR  ,
    UVM_INSTRUCTION_BYEQ  ,
    UVM_INSTRUCTION_BYGT  ,
    UVM_INSTRUCTION_BYLT  ,
    UVM_INSTRUCTION_BYGTS ,
    UVM_INSTRUCTION_BYLTS ,

    UVM_INSTRUCTION_SHPUSH,
    UVM_INSTRUCTION_SHDROP,
    UVM_INSTRUCTION_SHDUP ,
    UVM_INSTRUCTION_SHREV ,

    UVM_INSTRUCTION_SHADD ,
    UVM_INSTRUCTION_SHSUB ,
    UVM_INSTRUCTION_SHMUL ,
    UVM_INSTRUCTION_SHDIV ,
    UVM_INSTRUCTION_SHMOD ,
    UVM_INSTRUCTION_SHADDS,
    UVM_INSTRUCTION_SHSUBS,
    UVM_INSTRUCTION_SHMULS,
    UVM_INSTRUCTION_SHDIVS,
    UVM_INSTRUCTION_SHMODS,
    UVM_INSTRUCTION_SHASL ,
    UVM_INSTRUCTION_SHASR ,
    UVM_INSTRUCTION_SHAND ,
    UVM_INSTRUCTION_SHOR  ,
    UVM_INSTRUCTION_SHXOR ,
    UVM_INSTRUCTION_SHNOT ,
    UVM_INSTRUCTION_SHLSL ,
    UVM_INSTRUCTION_SHLSR ,
    UVM_INSTRUCTION_SHRL  ,
    UVM_INSTRUCTION_SHRR  ,
    UVM_INSTRUCTION_SHEQ  ,
    UVM_INSTRUCTION_SHGT  ,
    UVM_INSTRUCTION_SHLT  ,
    UVM_INSTRUCTION_SHGTS ,
    UVM_INSTRUCTION_SHLTS ,

    UVM_INSTRUCTION_INPUSH,
    UVM_INSTRUCTION_INDROP,
    UVM_INSTRUCTION_INDUP ,
    UVM_INSTRUCTION_INREV ,

    UVM_INSTRUCTION_INADD ,
    UVM_INSTRUCTION_INSUB ,
    UVM_INSTRUCTION_INMUL ,
    UVM_INSTRUCTION_INDIV ,
    UVM_INSTRUCTION_INMOD ,
    UVM_INSTRUCTION_INADDS,
    UVM_INSTRUCTION_INSUBS,
    UVM_INSTRUCTION_INMULS,
    UVM_INSTRUCTION_INDIVS,
    UVM_INSTRUCTION_INMODS,
    UVM_INSTRUCTION_INASL ,
    UVM_INSTRUCTION_INASR ,
    UVM_INSTRUCTION_INAND ,
    UVM_INSTRUCTION_INOR  ,
    UVM_INSTRUCTION_INXOR ,
    UVM_INSTRUCTION_INNOT ,
    UVM_INSTRUCTION_INLSL ,
    UVM_INSTRUCTION_INLSR ,
    UVM_INSTRUCTION_INRL  ,
    UVM_INSTRUCTION_INRR  ,
    UVM_INSTRUCTION_INEQ  ,
    UVM_INSTRUCTION_INGT  ,
    UVM_INSTRUCTION_INLT  ,
    UVM_INSTRUCTION_INGTS ,
    UVM_INSTRUCTION_INLTS ,

    UVM_INSTRUCTION_SZPUSH,
    UVM_INSTRUCTION_SZDROP,
    UVM_INSTRUCTION_SZDUP ,
    UVM_INSTRUCTION_SZREV ,

    UVM_INSTRUCTION_SZADD ,
    UVM_INSTRUCTION_SZSUB ,
    UVM_INSTRUCTION_SZMUL ,
    UVM_INSTRUCTION_SZDIV ,
    UVM_INSTRUCTION_SZMOD ,
    UVM_INSTRUCTION_SZADDS,
    UVM_INSTRUCTION_SZSUBS,
    UVM_INSTRUCTION_SZMULS,
    UVM_INSTRUCTION_SZDIVS,
    UVM_INSTRUCTION_SZMODS,
    UVM_INSTRUCTION_SZASL ,
    UVM_INSTRUCTION_SZASR ,
    UVM_INSTRUCTION_SZAND ,
    UVM_INSTRUCTION_SZOR  ,
    UVM_INSTRUCTION_SZXOR ,
    UVM_INSTRUCTION_SZNOT ,
    UVM_INSTRUCTION_SZLSL ,
    UVM_INSTRUCTION_SZLSR ,
    UVM_INSTRUCTION_SZRL  ,
    UVM_INSTRUCTION_SZRR  ,
    UVM_INSTRUCTION_SZEQ  ,
    UVM_INSTRUCTION_SZGT  ,
    UVM_INSTRUCTION_SZLT  ,
    UVM_INSTRUCTION_SZGTS ,
    UVM_INSTRUCTION_SZLTS ,

    UVM_INSTRUCTION_BYSTOREIMM,
    UVM_INSTRUCTION_BYSTORESTK,
    UVM_INSTRUCTION_BYFETCHIMM,
    UVM_INSTRUCTION_BYFETCHSTK,

    UVM_INSTRUCTION_SHSTOREIMM,
    UVM_INSTRUCTION_SHSTORESTK,
    UVM_INSTRUCTION_SHFETCHIMM,
    UVM_INSTRUCTION_SHFETCHSTK,

    UVM_INSTRUCTION_INSTOREIMM,
    UVM_INSTRUCTION_INSTORESTK,
    UVM_INSTRUCTION_INFETCHIMM,
    UVM_INSTRUCTION_INFETCHSTK,

    UVM_INSTRUCTION_SZSTOREIMM,
    UVM_INSTRUCTION_SZSTORESTK,
    UVM_INSTRUCTION_SZFETCHIMM,
    UVM_INSTRUCTION_SZFETCHSTK,

    UVM_INSTRUCTION_JMPIMM  ,
    UVM_INSTRUCTION_JMPSTK  ,
    UVM_INSTRUCTION_JMPZIMM ,
    UVM_INSTRUCTION_JMPZSTK ,
    UVM_INSTRUCTION_JMPNZIMM,
    UVM_INSTRUCTION_JMPNZSTK,

    UVM_INSTRUCTION_CALIMM,
    UVM_INSTRUCTION_CALSTK,
    UVM_INSTRUCTION_RET   ,

    UVM_INSTRUCTION_BYIN,
    UVM_INSTRUCTION_SHIN,
    UVM_INSTRUCTION_ININ,
    UVM_INSTRUCTION_SZIN,

    UVM_INSTRUCTION_BYOUTIMM,
    UVM_INSTRUCTION_BYOUTSTK,
    UVM_INSTRUCTION_SHOUTIMM,
    UVM_INSTRUCTION_SHOUTSTK,
    UVM_INSTRUCTION_INOUTIMM,
    UVM_INSTRUCTION_INOUTSTK,
    UVM_INSTRUCTION_SZOUTIMM,
    UVM_INSTRUCTION_SZOUTSTK

} uvm_instruction_t;

UVM_LINKAG extern const uvm_instruction_t first_uvm_instruction;

UVM_LINKAG extern const uvm_instruction_t last_uvm_instruction;

UVM_LINKAG extern const char *uvm_instruction2str[];

UVM_LINKAG const char *uvm_instruction2string(uvm_instruction_t instruction);

#ifdef __cplusplus
}
#endif

#endif/*UVMINSTR_H*/
